### ISSUE TITLE
Allow overrides for default mechanisms and morphology

### ISSUE THREAD

**Issue by frthjf** [GazzolaLab/MiV-Simulator#36]
Like with the YAML configuration, there should be a way to progressively override the default mechanism and morphology without duplication all of the configuration files. For example, a user might change the `cat.mod` mechanism in their code base, while still falling back on the default mechanism in all other cases.

Proposed implementation:
- Copy defaults into tmp directory within venv, merge in user files to potentially override defaults
- Compile dll and return location of tmp directory to be used instead of user directory
- Compute a directory hash of user directory (likely using a [suitable subprocess call](https://stackoverflow.com/questions/545387/linux-compute-a-single-hash-for-a-given-folder-contents)) to avoid unnecessary recompilation

**Comment by iraikov** [comment]
Generally speaking, a set of cell morphologies will be associated with particular synaptic distributions and connectivity, so it makes little sense to me to have a method to change only the morphologies for a particular model. Are you thinking of the case of simulating a reduced model that inherits its synapses and connectivity from a full morphology?
